import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'MinhB1910412',
      email: 'minhpro207@yahoo.com',
      password: bcrypt.hashSync('adcbyminhh'),
      isAdmin: true,
    },
  ],

  products: [
    {
      name: 'Chicken',
      slug: 'food-chicken',
      category: 'food',
      image: 'images/chicken.png',
      price: 5,
      brand: 'KFC',
      rating: 3.5,
      numReviews: 8,
      countInStock: 8,
      description: 'Delicious meal',
    },
    {
      name: 'Pepsi',
      slug: 'drink-pepsi',
      category: 'drink',
      image: 'images/pepsi.png',
      price: 1,
      brand: 'Pepsi',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'Delicious Drink',
    },
    {
      name: 'Pizza',
      slug: 'food-pizza',
      category: 'food',
      image: 'images/pizza.jpg',
      price: 6,
      brand: 'Pizza Hut',
      rating: 3.5,
      numReviews: 2,
      countInStock: 10,
      description: 'Delicious meal',
    },
    {
      name: 'Sushi',
      slug: 'food-sushi',
      category: 'food',
      image: 'images/sushi.jpg',
      price: 8,
      brand: 'Japanese Restaurant',
      rating: 5.0,
      numReviews: 2,
      countInStock: 4,
      description: 'Delicious meal',
    },
    {
      name: 'Banana',
      slug: 'fruit-banana',
      category: 'Market',
      image: 'images/banana.png',
      price: 5,
      brand: 'fruit',
      rating: 3.5,
      numReviews: 1,
      countInStock: 12,
      description: 'Delicious kind of fruit',
    },
    {
      name: 'Watermelon',
      slug: 'fruit-watermelon',
      category: 'fruit',
      image: 'images/watermelon.png',
      price: 5,
      brand: 'Market',
      rating: 3.5,
      numReviews: 2,
      countInStock: 11,
      description: 'Delicious meal',
    },
  ],
};

export default data;
